/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class command_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public short thrust;
    public short roll;
    public short pitch;
    public short yaw;
 
    public command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x97e90da8496ed16dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.command_t.class))
            return 0L;
 
        classes.add(lcmtypes.command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeShort(this.thrust); 
 
        outs.writeShort(this.roll); 
 
        outs.writeShort(this.pitch); 
 
        outs.writeShort(this.yaw); 
 
    }
 
    public command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.command_t o = new lcmtypes.command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.thrust = ins.readShort();
 
        this.roll = ins.readShort();
 
        this.pitch = ins.readShort();
 
        this.yaw = ins.readShort();
 
    }
 
    public lcmtypes.command_t copy()
    {
        lcmtypes.command_t outobj = new lcmtypes.command_t();
        outobj.timestamp = this.timestamp;
 
        outobj.thrust = this.thrust;
 
        outobj.roll = this.roll;
 
        outobj.pitch = this.pitch;
 
        outobj.yaw = this.yaw;
 
        return outobj;
    }
 
}

