// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "command_t.h"

static int __command_t_hash_computed;
static int64_t __command_t_hash;

int64_t __command_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __command_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__command_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x97e90da8496ed16dLL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __command_t_get_hash(void)
{
    if (!__command_t_hash_computed) {
        __command_t_hash = __command_t_hash_recursive(NULL);
        __command_t_hash_computed = 1;
    }

    return __command_t_hash;
}

int __command_t_encode_array(void *buf, int offset, int maxlen, const command_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].thrust), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int command_t_encode(void *buf, int offset, int maxlen, const command_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __command_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __command_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __command_t_encoded_array_size(const command_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int16_t_encoded_array_size(&(p[element].thrust), 1);

        size += __int16_t_encoded_array_size(&(p[element].roll), 1);

        size += __int16_t_encoded_array_size(&(p[element].pitch), 1);

        size += __int16_t_encoded_array_size(&(p[element].yaw), 1);

    }
    return size;
}

int command_t_encoded_size(const command_t *p)
{
    return 8 + __command_t_encoded_array_size(p, 1);
}

int __command_t_decode_array(const void *buf, int offset, int maxlen, command_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].thrust), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].yaw), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __command_t_decode_array_cleanup(command_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int16_t_decode_array_cleanup(&(p[element].thrust), 1);

        __int16_t_decode_array_cleanup(&(p[element].roll), 1);

        __int16_t_decode_array_cleanup(&(p[element].pitch), 1);

        __int16_t_decode_array_cleanup(&(p[element].yaw), 1);

    }
    return 0;
}

int command_t_decode(const void *buf, int offset, int maxlen, command_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __command_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __command_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int command_t_decode_cleanup(command_t *p)
{
    return __command_t_decode_array_cleanup(p, 1);
}

int __command_t_clone_array(const command_t *p, command_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int16_t_clone_array(&(p[element].thrust), &(q[element].thrust), 1);

        __int16_t_clone_array(&(p[element].roll), &(q[element].roll), 1);

        __int16_t_clone_array(&(p[element].pitch), &(q[element].pitch), 1);

        __int16_t_clone_array(&(p[element].yaw), &(q[element].yaw), 1);

    }
    return 0;
}

command_t *command_t_copy(const command_t *p)
{
    command_t *q = (command_t*) malloc(sizeof(command_t));
    __command_t_clone_array(p, q, 1);
    return q;
}

void command_t_destroy(command_t *p)
{
    __command_t_decode_array_cleanup(p, 1);
    free(p);
}

int command_t_publish(lcm_t *lc, const char *channel, const command_t *p)
{
      int max_data_size = command_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = command_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _command_t_subscription_t {
    command_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void command_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    command_t p;
    memset(&p, 0, sizeof(command_t));
    status = command_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding command_t!!!\n", status);
        return;
    }

    command_t_subscription_t *h = (command_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    command_t_decode_cleanup (&p);
}

command_t_subscription_t* command_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    command_t_handler_t f, void *userdata)
{
    command_t_subscription_t *n = (command_t_subscription_t*)
                       malloc(sizeof(command_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 command_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg command_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int command_t_subscription_set_queue_capacity (command_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int command_t_unsubscribe(lcm_t *lcm, command_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe command_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

