// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "transmitter_t.h"

static int __transmitter_t_hash_computed;
static int64_t __transmitter_t_hash;

int64_t __transmitter_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __transmitter_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__transmitter_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x94eb226dd91614d6LL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __transmitter_t_get_hash(void)
{
    if (!__transmitter_t_hash_computed) {
        __transmitter_t_hash = __transmitter_t_hash_recursive(NULL);
        __transmitter_t_hash_computed = 1;
    }

    return __transmitter_t_hash;
}

int __transmitter_t_encode_array(void *buf, int offset, int maxlen, const transmitter_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch1), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch2), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch3), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch4), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch5), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch6), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ch7), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int transmitter_t_encode(void *buf, int offset, int maxlen, const transmitter_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __transmitter_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __transmitter_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __transmitter_t_encoded_array_size(const transmitter_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch0), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch1), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch2), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch3), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch4), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch5), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch6), 1);

        size += __int16_t_encoded_array_size(&(p[element].ch7), 1);

    }
    return size;
}

int transmitter_t_encoded_size(const transmitter_t *p)
{
    return 8 + __transmitter_t_encoded_array_size(p, 1);
}

int __transmitter_t_decode_array(const void *buf, int offset, int maxlen, transmitter_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch1), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch2), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch3), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch4), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch5), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch6), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ch7), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __transmitter_t_decode_array_cleanup(transmitter_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch0), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch1), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch2), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch3), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch4), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch5), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch6), 1);

        __int16_t_decode_array_cleanup(&(p[element].ch7), 1);

    }
    return 0;
}

int transmitter_t_decode(const void *buf, int offset, int maxlen, transmitter_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __transmitter_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __transmitter_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int transmitter_t_decode_cleanup(transmitter_t *p)
{
    return __transmitter_t_decode_array_cleanup(p, 1);
}

int __transmitter_t_clone_array(const transmitter_t *p, transmitter_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int16_t_clone_array(&(p[element].ch0), &(q[element].ch0), 1);

        __int16_t_clone_array(&(p[element].ch1), &(q[element].ch1), 1);

        __int16_t_clone_array(&(p[element].ch2), &(q[element].ch2), 1);

        __int16_t_clone_array(&(p[element].ch3), &(q[element].ch3), 1);

        __int16_t_clone_array(&(p[element].ch4), &(q[element].ch4), 1);

        __int16_t_clone_array(&(p[element].ch5), &(q[element].ch5), 1);

        __int16_t_clone_array(&(p[element].ch6), &(q[element].ch6), 1);

        __int16_t_clone_array(&(p[element].ch7), &(q[element].ch7), 1);

    }
    return 0;
}

transmitter_t *transmitter_t_copy(const transmitter_t *p)
{
    transmitter_t *q = (transmitter_t*) malloc(sizeof(transmitter_t));
    __transmitter_t_clone_array(p, q, 1);
    return q;
}

void transmitter_t_destroy(transmitter_t *p)
{
    __transmitter_t_decode_array_cleanup(p, 1);
    free(p);
}

int transmitter_t_publish(lcm_t *lc, const char *channel, const transmitter_t *p)
{
      int max_data_size = transmitter_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = transmitter_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _transmitter_t_subscription_t {
    transmitter_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void transmitter_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    transmitter_t p;
    memset(&p, 0, sizeof(transmitter_t));
    status = transmitter_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding transmitter_t!!!\n", status);
        return;
    }

    transmitter_t_subscription_t *h = (transmitter_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    transmitter_t_decode_cleanup (&p);
}

transmitter_t_subscription_t* transmitter_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    transmitter_t_handler_t f, void *userdata)
{
    transmitter_t_subscription_t *n = (transmitter_t_subscription_t*)
                       malloc(sizeof(transmitter_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 transmitter_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg transmitter_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int transmitter_t_subscription_set_queue_capacity (transmitter_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int transmitter_t_unsubscribe(lcm_t *lcm, transmitter_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe transmitter_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

