// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "var_t.h"

static int __var_t_hash_computed;
static int64_t __var_t_hash;

int64_t __var_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __var_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__var_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x8f2f3ffe876c646aLL
         + __int64_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __var_t_get_hash(void)
{
    if (!__var_t_hash_computed) {
        __var_t_hash = __var_t_hash_recursive(NULL);
        __var_t_hash_computed = 1;
    }

    return __var_t_hash;
}

int __var_t_encode_array(void *buf, int offset, int maxlen, const var_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].angle, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].angular_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int var_t_encode(void *buf, int offset, int maxlen, const var_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __var_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __var_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __var_t_encoded_array_size(const var_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int16_t_encoded_array_size(p[element].accel, 3);

        size += __int32_t_encoded_array_size(p[element].angle, 3);

        size += __int32_t_encoded_array_size(p[element].angular_vel, 3);

    }
    return size;
}

int var_t_encoded_size(const var_t *p)
{
    return 8 + __var_t_encoded_array_size(p, 1);
}

int __var_t_decode_array(const void *buf, int offset, int maxlen, var_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].angle, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].angular_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __var_t_decode_array_cleanup(var_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int16_t_decode_array_cleanup(p[element].accel, 3);

        __int32_t_decode_array_cleanup(p[element].angle, 3);

        __int32_t_decode_array_cleanup(p[element].angular_vel, 3);

    }
    return 0;
}

int var_t_decode(const void *buf, int offset, int maxlen, var_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __var_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __var_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int var_t_decode_cleanup(var_t *p)
{
    return __var_t_decode_array_cleanup(p, 1);
}

int __var_t_clone_array(const var_t *p, var_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int16_t_clone_array(p[element].accel, q[element].accel, 3);

        __int32_t_clone_array(p[element].angle, q[element].angle, 3);

        __int32_t_clone_array(p[element].angular_vel, q[element].angular_vel, 3);

    }
    return 0;
}

var_t *var_t_copy(const var_t *p)
{
    var_t *q = (var_t*) malloc(sizeof(var_t));
    __var_t_clone_array(p, q, 1);
    return q;
}

void var_t_destroy(var_t *p)
{
    __var_t_decode_array_cleanup(p, 1);
    free(p);
}

int var_t_publish(lcm_t *lc, const char *channel, const var_t *p)
{
      int max_data_size = var_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = var_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _var_t_subscription_t {
    var_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void var_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    var_t p;
    memset(&p, 0, sizeof(var_t));
    status = var_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding var_t!!!\n", status);
        return;
    }

    var_t_subscription_t *h = (var_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    var_t_decode_cleanup (&p);
}

var_t_subscription_t* var_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    var_t_handler_t f, void *userdata)
{
    var_t_subscription_t *n = (var_t_subscription_t*)
                       malloc(sizeof(var_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 var_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg var_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int var_t_subscription_set_queue_capacity (var_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int var_t_unsubscribe(lcm_t *lcm, var_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe var_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

